### ISSUE TITLE
Show sprite at 0% full width

### ISSUE THREAD

**Issue by leonidkiritschenko** [egeinanc/dragonball-progressbar#15]
Currently: When tests or any other task is executed and only shows 0% most of the time, it looks like the loading bar is broken, because no sprite is visible.

To-Be: At 0% the sprite should be fully visible and add with further percentage/

Code: here just remove "- imageIcon.getIconWidth()" 
https://github.com/egeinanc/dragonball-progressbar/blob/8d4e664a8b5a1ad56ee43b75ce905024751df6bb/src/main/java/DbzProgressBarUi.java#L87

**Comment by egeinanc** [comment]
Thank you for the issue. A fix for this issue will be included in the next update :)
