### ISSUE TITLE
Compatibility with IntelliJ IDEA version 2022.3

### ISSUE THREAD

**Issue by Mokette** [egeinanc/dragonball-progressbar#16]
Please could you make it compatible with the last intelliJ IDEA version 2022.3 cause it currently cannont be installed on this version

By simply edit the gradle.properties file and set `pluginUntilBuild=223.*`

**Comment by egeinanc** [comment]
A new Version has been uploaded. It's currently in review by JetBrains. It should be available in two business days :)

Thank you for the issue  @Mokette :)
