### ISSUE TITLE
Sprite does not fit

### ISSUE THREAD

**Issue by juanlubf** [egeinanc/dragonball-progressbar#30]
Since last update, the sprite does not fit in the bar 
<img width="436" alt="image" src="https://github.com/egeinanc/dragonball-progressbar/assets/11267762/bca52da5-23e2-4bdf-bce8-7e5bdf301416">

**Comment by egeinanc** [comment]
Thank you for the issue. Somehow the Imageicon constructor acts different in different environments. (https://github.com/egeinanc/dragonball-progressbar/issues/18#issuecomment-1682346825)

I will dig in this problem.

**Comment by egeinanc** [comment]
Hi @juanlubf 
I have uploaded a new release which is currently being reviewed by JetBrains. The next update should fix this issue. Until then I keep this issue open.
Thanks again for the issue :)
